# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 本地数据源
    url: jdbc:mysql://localhost:3306/rpsm?userUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    # 远程数据源
#    url: jdbc:mysql://47.108.210.135:33060/rpsm?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    username: rpsm
#    password: rpsm
  jpa:
    database: MYSQL
mybatis:
  type-aliases-package: com.gzy.rpsm.property.pojo
  mapper-locations: /mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
